title: Mochi blog
description: welcome to my blog! you can see what have I done recently
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
repository: github_username/github_username.github.io
github_url: https://github.com/github_username
url: https://github_username.github.io
